theme = "cj"

[editor]
auto-format = false
auto-save = true
color-modes = true
completion-trigger-len = 1
idle-timeout = 0  # for instant autocompletion
cursorline = true
mouse = false
true-color = true
auto-pairs = false

[editor.statusline]
left = ["mode", "spinner"]
right = ["diagnostics"]
mode.insert = "I"
mode.normal = "N"
mode.select = "S"

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[keys.normal]
w = "move_line_up"
a = "move_char_left"
s = "move_line_down"
d = "move_char_right"

W = ["move_line_up", "move_line_up", "move_line_up", "move_line_up", "move_line_up"]
A = "move_prev_word_end"
S = ["move_line_down", "move_line_down", "move_line_down", "move_line_down", "move_line_down"]
D = "move_next_word_start"

q = "extend_to_line_start"
e = "extend_to_line_end"
Q = "insert_at_line_start"
E = "insert_at_line_end"

x = "delete_selection"
v = "extend_line_below"
V = "select_mode"
C-s = "select_regex"

C-a = "select_all"

";" = "command_palette"

g = { w = "goto_file_start", s = "goto_file_end", a = "goto_line_start", d = "goto_line_end" }

[keys.select]
w = "extend_line_up"
a = "extend_char_left"
s = "extend_line_down"
d = "extend_char_right"

W = "extend_line_up"
A = "extend_prev_word_end"
S = "extend_line_down"
D = "extend_next_word_start"

q = "extend_to_line_start"
e = "extend_to_line_end"
Q = "extend_to_line_start"
E = "extend_to_line_end"

x = "delete_selection"
