# Source: https://github.com/estin/simple-completion-language-server
# Build: `cargo build --release`
[language-server.buffer]
  command = "${home}/dev/simple-completion-language-server/target/release/simple-completion-language-server"

  [language-server.buffer.config]
    max_completion_items = 500
    feature_snippets = false
    feature_unicode_input = false

# Source: https://github.com/vlabo/cspell-lsp
# Build: `npm install; npm run build`
[language-server.cspell]
  command = "node"
  args = [ "${home}/dev/cspell-lsp/index.js", "--stdio" ]

# Install: ruff-lsp
[language-server.ruff]
  command = "ruff-lsp"

# Install: pyright
[language-server.pyright]
  command = "pyright-langserver"

  [language-server.pyright.config.python.analysis]
    typeCheckingMode = "strict"

  [language-server.pyright.config.python.analysis.diagnosticSeverityOverrides]
    reportMissingImports = false
    reportMissingTypeStubs = false
    reportUntypedFunctionDecorator = false
    reportUnknownVariableType = false

    # Covered by ruff
    reportUnusedImport = false

# Install: python-lsp-server, python-rope, python-pylsp-mypy
[language-server.pylsp]
  command = "pylsp"

  [language-server.pylsp.config.pylsp.plugins]
    # Disable unused plugins
    autopep8.enabled = false
    flake8.enabled = false
    mccabe.enabled = false
    preload.enabled = false
    pycodestyle.enabled = false
    pyflakes.enabled = false
    yapf.enabled = false

    # Settings
    [language-server.pylsp.config.pylsp.plugins.jedi_completion]
      include_params = false
      fuzzy = true
      resolve_at_most = 100

[language-server.zls]
  command = "zls"

  [language-server.zls.config]
    enable_autofix = true
    enable_inlay_hints = false
    enable_argument_placeholders = false
    warn_style = true

[language-server.rust-analyzer]
  command = "${home}/.cargo/bin/ra-multiplex"

  [language-server.rust-analyzer.config]
    cachePriming.enable = false
    completion.callable.snippets = "none"
    completion.fullFunctionSignatures.enable = false  # make list shorter
    completion.limit = 1024
    completion.postfix.enable = false  # disable postfix snippets
    completion.hideDeprecated = true

    imports.preferNoStd = true

    hover.actions.run.enable = false
    hover.show.fields = 10

    inlayHints.chainingHints.enable = false
    inlayHints.closingBraceHints.enable = false
    inlayHints.genericParameterHints.const.enable = false
    inlayHints.typeHints.enable = false
    inlayHints.parameterHints.enable = false
    inlayHints.renderColons = false

    lens.enable = false

    lru.capacity = 512

    diagnostics.experimental.enable = true
    diagnostics.styleLints.enable = true

    check.command = "clippy"

    # Use separate target directory for rust-analyzer to remove interferences with cargo
    cargo.targetDir = true

    cargo.allTargets = false

    rustfmt.extraArgs = [
      "--config=empty_item_single_line=false",
      "--config=wrap_comments=true",
      "--config=condense_wildcard_suffixes=true",
      "--config=enum_discrim_align_threshold=10",
      "--config=format_code_in_doc_comments=true",
      "--config=hex_literal_case=Upper",
      "--config=max_width=80",
      "--config=reorder_impl_items=true",
      "--config=group_imports=StdExternalCrate",
      "--config=use_field_init_shorthand=true",
    ]

[[language]]
  name = "python"
  auto-format = true
  language-servers = [
    # Completions, documentation, go to definition
    { name = "pylsp", except-features = [ "diagnostics", "format" ] },
    # Linting, fixes, formatting
    "ruff",
    # Type checking
    { name = "pyright", only-features = [ "diagnostics" ] },
    "buffer",
    "cspell",
  ]

[[language]]
  name = "bash"
  # Install: bash-language-server
  language-servers = [ "bash-language-server", "buffer", "cspell" ]

[[language]]
  name = "dockerfile"
  # Install: dockerfile-language-server (aur)
  language-servers = [ "docker-langserver", "buffer", "cspell" ]

[[language]]
  name = "markdown"
  # Install: marksman
  language-servers = [ "marksman", "buffer", "cspell" ]
  roots = ["README.md"]

[[language]]
  name = "yaml"
  language-servers = [ "buffer", "cspell" ]

[[language]]
  name = "html"
  language-servers = [ "buffer", "cspell" ]

[[language]]
  name = "toml"
  language-servers = [ "buffer", "cspell" ]

[[language]]
  name = "git-commit"
  rulers = []
  language-servers = [ "buffer", "cspell" ]

[[language]]
  name = "zig"
  # Install: zls
  language-servers = [ "zls", "buffer", "cspell" ]

[[language]]
  name = "rust"
  # Install: rust-analyzer, ra-multiplex
  language-servers = [ "rust-analyzer", "buffer", "cspell" ]
