[language-server.pylsp]
command = "pylsp"

[language-server.pylsp.config.plugins]
autopep8 = { enabled = false }
mccabe = { enabled = false }
preload = { enabled = false }
pycodestyle = { enabled = false }
pyflakes = { enabled = false }
yapf = { enabled = false }
flake8 = { enabled = true }
jedi_completion = { fuzzy = true, resolve_at_most = 10 }
ruff = { enabled = true }
mypy = { enabled = true, dmypy = true }
black = { enabled = true, preview = true }

[[language]]
name = "python"
language-servers = [
  { name = "pylsp" },
]

[[language]]
name = "git-commit"
rulers = []
