# Syntax
"comment" = "fg-dim"

"type" = "fg-half-dim"
"constructor" = "yellow"

"constant.numeric" = "yellow"
"constant.builtin" = "orange"

"string" = "green"
"constant.character.escape" = "pink"
"string.special" = "green"

"variable.builtin" = "orange"
"variable.parameter" = "cyan"

"function" = "purple"
"function.method" = "fg"
"function.builtin" = "orange"

"punctuation" = "fg-half-dim"
"punctuation.bracket" = "fg-dim"
"punctuation.special" = "pink"
"operator" = "fg-dim"
"label" = "fg-dim"

"keyword" = "blue"
"namespace" = "fg"

"markup.heading" = "orange"
"markup.list" = "fg-dim"
"markup.list.unchecked" = "red"
"markup.bold" = "red"
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = { underline.style = "line" }
"markup.quote" = "fg-half-dim"
"markup.raw.inline" = "yellow"

"special" = "blue"  # also, highlight in file picker

# HTML
"attribute" = "yellow"
"string.regexp" = "pink"
"tag" = "purple"

# Diff
"diff.plus" = "green"
"diff.minus" = "red"
"diff.delta" = "purple"

# Background
"ui.background" = { bg = "bg", fg = "fg" }

# Cursor
"ui.cursor" = { bg = "fg-dim", fg = "bg" }
"ui.selection" = { bg = "bg-sel" }
"ui.cursor.match" = { fg = "purple", underline.style = "line" }
"ui.cursorline.primary" = { bg = "bg-dim" }

# Gutter
"ui.linenr" = "fg-dim"
"ui.linenr.selected" = "fg"

"error" = "red"
"warning" = "orange"
"info" = "yellow"  # for TODO highlighting
"hint" = "gray"

# Diagnostics
"diagnostic.error" = { fg = "red", underline.style = "line" }
"diagnostic.warning" = { fg = "orange", underline.style = "line" }
"diagnostic.info" = { underline.style = "line" }
"diagnostic.hint" = { underline.style = "line" }

# Statusline
"ui.statusline" = { fg = "fg" }
"ui.statusline.insert" = { bg = "yellow", fg = "bg" }
"ui.statusline.select" = { bg = "purple", fg = "bg" }

# Whitespace
"ui.virtual.whitespace" = "red"
"ui.virtual.indent-guide" = "bg-sel"
"ui.virtual.ruler" = { bg = "bg-sel" }

# Windows & Popups
"ui.popup" = { bg = "bg-dim", fg = "fg-half-dim" }
"ui.popup.info" = { bg = "bg", fg = "fg-half-dim" }
"ui.window" = { fg = "fg-dim" }
"ui.help" = { fg = "fg-half-dim", bg = "bg-dim" }

"ui.text" = "fg"
"ui.text.focus" = { fg = "fg", bg = "bg-sel" }
"ui.text.inactive" = "fg-dim"

"ui.menu" = { fg = "fg-half-dim", bg = "bg-dim" }
"ui.menu.selected" = { fg = "fg", bg = "bg-sel" }
"ui.menu.scroll" = { bg = "bg-sel", fg = "bg-sel" }

"ui.highlight" = { bg = "bg-dim" }  # highlight in file picker

# Jump labels
"ui.virtual.jump-label" = { fg = "yellow", modifiers = [ "reversed" ] }

[palette]
  bg          = "#${bg}"
  bg-dim      = "#${bg_dim}"  # panels, line highlighting
  bg-sel      = "#${bg_sel}"  # selection

  fg          = "#${fg}"
  fg-half-dim = "#${fg_half_dim}"  # some menus
  fg-dim      = "#${fg_dim}"       # comments

  red         = "#${red}"     # errors, important stuff
  orange      = "#${orange}"  # warnings, less important stuff
  yellow      = "#${yellow}"  # highlighting
  green       = "#${green}"   # strings, good stuff
  cyan        = "#${cyan}"    # arguments
  blue        = "#${blue}"    # keywords
  purple      = "#${purple}"  # functions and tags
  pink        = "#${pink}"    # string interpolation, regexps
