# SCALE: 14.5
font = Noto Sans Mono Light:pixelsize=@scale(14.5)
prompt = ""
icons-enabled = no
lines = 10
width = 50
# SCALE: 16
horizontal-pad = @scale(16)
# SCALE: 16
vertical-pad = @scale(16)
anchor = top
# SCALE: 100
y-margin = @scale(100)
# SCALE: 8
inner-pad = @scale(8)
# SCALE: 16.5
line-height = @scale(16.5)

[colors]
  background = ${bg_dim_more}ff
  text = ${fg_half_dim}ff
  prompt = ff0000ff
  placeholder = ff0000ff
  input = ${blue}ff
  match = ${purple}ff
  selection = ${bg_dim_more}ff
  selection-text = ${blue}ff
  selection-match = ${purple}ff
  border = ${bg_dim_more}ff

[border]
  width = 0
  # SCALE: 12
  radius = @scale(12)
