install:
  image: archlinux/base

  before_script:
    - pacman -Sy --quiet --noconfirm git zsh sudo > /dev/null
    - touch settings.sh

  script:
    - sh tools/one-command-install.sh
    - "[ ! -f ~/.zshenv ]"
    - "[ -f ~/.pam_environment ]"
