install:
  image: archlinux/base

  before_script:
    - pacman -Sy --noconfirm git zsh
    - touch settings.sh

  script:
    - zsh tools/install.zsh
    - "[ -f tools/settings.sh ]"
    - "[ -f ~/.zshenv ]"
