[colors]
  bg          = "1d2433"
  bg_dim      = "1a202e"
  bg_dim_more = "171c29"
  bg_sel      = "293145"

  bg_remove   = "332127"
  bg_add      = "1E2B1E"

  fg          = "bfd3ff"
  fg_half_dim = "54678c"
  fg_dim      = "3d4a66"

  red         = "D0879D"
  orange      = "D0B1A2"
  yellow      = "CDD2AF"
  green       = "9FD6B6"
  cyan        = "acd9ec"
  blue        = "92b7ea"
  purple      = "AD9BEA"
  pink        = "CD9BCC"

[hosts.iota]
  output_name = "HDMI-A-1"
  output_mode = "2560x1440@99.946"

  ui_scale = 2.0

[hosts.zeta]
  output_name = "eDP-1"
  output_mode = "1920x1200@60.096"

  ui_scale = 1.5

[hosts.termux]
