[options]
AurOnly
SkipReview

# List best packages closer to the prompt
SortBy=votes
BottomUp

# Skip check step and dependencies
NoCheck

# Exit after first package build failed
FailFast

# Update "devel" packages
Devel
DevelSuffixes = -git -cvs -svn -bzr -darcs -always -hg -fossil
