[general]

temp-day=5700
temp-night=2500
fade=1

gamma-day=1.0
gamma-night=0.85

# Not working in my setup
brightness-day=1.0
brightness-night=1.0

# Equivalent to 8:00-10:00 and 20:00-22:00 BKK
dawn-time=1:00-3:00
dusk-time=13:00-15:00
