"inherits" = "base16_transparent"

"ui.text" = "light-gray"
"ui.linenr" = "gray"
"ui.linenr.selected" = "light-gray"
"ui.popup" = "gray"
"ui.selection" = { fg = "light-gray", bg = "gray", modifiers = [] }

"punctuation.bracket" = "white"
