"inherits" = "base16_transparent"

"ui.text" = "light-gray"
"ui.linenr" = "gray"
"ui.linenr.selected" = "light-gray"
"ui.popup" = { fg = "gray", bg = "#3B4252" }
"ui.help" = { bg = "#3B4252" }
"ui.menu" = { bg = "#3B4252" }
"ui.selection" = { fg = "light-gray", bg = "gray", modifiers = [] }

"markup.italic" = { fg = "light-magenta", modifiers = ["bold"] }
"punctuation.bracket" = "white"
"comment" = "gray"
