# VAR: bg
background : #{bg}
# VAR: fg
foreground : #{fg}
# VAR: bg
color0  : #{bg}
# VAR: red
color1  : #{red}
# VAR: green
color2  : #{green}
# VAR: yellow
color3  : #{yellow}
# VAR: blue
color4  : #{blue}
# VAR: purple
color5  : #{purple}
# VAR: cyan
color6  : #{cyan}
# VAR: fg_half_dim
color7  : #{fg_half_dim}
# VAR: fg_dim
color8  : #{fg_dim}
# VAR: orange
color9  : #{orange}
# VAR: green
color10 : #{green}
# VAR: yellow
color11 : #{yellow}
# VAR: blue
color12 : #{blue}
# VAR: pink
color13 : #{pink}
# VAR: cyan
color14 : #{cyan}
# VAR: fg
color15 : #{fg}
