# === Wayland support ===

--ozone-platform=wayland

# === Hardware acceleration tweaks ===

# HW accelerated video encoding is not needed, but it does not hurt
--enable-features=AcceleratedVideoDecodeLinuxGL,AcceleratedVideoEncoder

# === Other ===

--force-device-scale-factor=1.5
--password-store=basic
