#!/usr/bin/env sh

exec /usr/bin/ssh \
  -F "${XDG_CONFIG_HOME}/ssh/config" \
  -o "IdentityFile=${XDG_DATA_HOME}/ssh/id_rsa" \
  -o "UserKnownHostsFile=${XDG_DATA_HOME}/ssh/known_hosts" \
  -o "ControlPath=${XDG_RUNTIME_DIR}/ssh/sockets/socket-%r@%h:%p" \
  "$@"
