[foot*]
app_layout.left = up
app_layout.right = down
app_layout.up = S-pagedown
app_layout.down = S-pageup

app_layout.x = overload(app_extra_layer, enter)
app_layout.b = C-c
# FREE: app_layout.y
# FREE: app_layout.a

# [foot].app_layer
app_layer.left = up
app_layer.right = down
app_layer.up = S-pagedown
app_layer.down = S-pageup

app_layer.x = overload(app_extra_layer, enter)
app_layer.b = C-c
# FREE: app_layer.y
# FREE: app_layer.a

[google-chrome*]
app_layout.left = w
app_layout.right = s
app_layout.up = d
app_layout.down = a

app_layout.x = overload(app_extra_layer, f)
app_layout.b = esc
app_layout.y = n
# FREE: app_layout.a

# [google-chrome].extra
app_extra_layer.b = C-w

# [google-chrome].app_layer
app_layer.left = w
app_layer.right = s
app_layer.up = d
app_layer.down = a

app_layer.x = overload(app_extra_layer, f)
app_layer.b = esc
app_layer.y = n
# FREE: app_layout.a

[element]
app_layout.left = A-up
app_layout.right = A-down
app_layout.up = pagedown
app_layout.down = pageup

app_layout.x = overload(app_extra_layer, enter)
app_layout.b = macro(C-a backspace)
# FREE: app_layout.y
# FREE: app_layout.a

# [element].app_layer
app_layer.left = A-up
app_layer.right = A-down
app_layer.up = pagedown
app_layer.down = pageup

app_layer.x = overload(app_extra_layer, enter)
app_layer.b = macro(C-a backspace)
# FREE: app_layer.y
# FREE: app_layer.a

[org-telegram-desktop]
app_layout.left = A-up
app_layout.right = A-down
app_layout.up = pagedown
app_layout.down = pageup

app_layout.x = overload(app_extra_layer, enter)
app_layout.b = macro(C-a backspace)
# FREE: app_layout.y
# FREE: app_layout.a

# [telegram].app_layer
app_layer.left = A-up
app_layer.right = A-down
app_layer.up = pagedown
app_layer.down = pageup

app_layer.x = overload(app_extra_layer, enter)
app_layer.b = macro(C-a backspace)
# FREE: app_layer.y
# FREE: app_layer.a
