[General]
buttons=@Variant(\0\0\0\x7f\0\0\0\vQList<int>\0\0\0\0\t\0\0\0\0\0\0\0\x1\0\0\0\x2\0\0\0\x3\0\0\0\x5\0\0\0\x6\0\0\0\xf\0\0\0\x16\0\0\0\x13)
contrastOpacity=188
disabledTrayIcon=true
insecurePixelate=false
jpegQuality=75
saveAfterCopy=true
savePath=/home/cj/screenshots
showAbortNotification=false
showDesktopNotification=false
showHelp=false
showStartupLaunchMessage=false
# VAR: blue
uiColor=#{blue}
# VAR: bg
# VAR: bg_dim
# VAR: bg_dim_more
# VAR: bg_sel
# VAR: bg_remove
# VAR: bg_add
# VAR: fg
# VAR: fg_half_dim
# VAR: fg_dim
# VAR: red
# VAR: orange
# VAR: yellow
# VAR: green
# VAR: cyan
# VAR: blue
# VAR: purple
# VAR: pink
userColors=picker, #{bg}, #{bg_dim}, #{bg_dim_more}, #{bg_sel}, #{bg_remove}, #{bg_add}, #{fg}, #{fg_half_dim}, #{fg_dim}, #{red}, #{orange}, #{yellow}, #{green}, #{cyan}, #{blue}, #{purple}, #{pink}
