#!/bin/zsh -l

LOGPATH="${XDG_RUNTIME_DIR}/mpd"
mkdir -p "${LOGPATH}"

{
  sleep 1.0
  cd "${HOME}/@storage/@music"
  mpc update
  sleep 10.0
  mpc add *
  mpc repeat
  mpc random
  mpc play
} &

exec mpd --no-daemon --verbose --stderr 2>&1 >> "${LOGPATH}/mpd.log"
