#!/usr/bin/sh

. "${CJ_DOTFILES}/assets/colors.sh"
. "${CJ_DOTFILES}/settings.sh"

# Startup

if [[ -f "${CJ_DOTFILES}/local.sh" ]]; then
  . "${CJ_DOTFILES}/local.sh"
fi

feh --no-fehbg --bg-scale "${CJ_WALLPAPER}"

setxkbmap -layout "us,ru" -option "grp:caps_toggle,grp_led:caps,grp_led:scroll,grp_led:num,compose:ralt"

if command -v picom > /dev/null; then
  picom --daemon --experimental-backends
fi

xrdb -merge "${CJ_DOTFILES}/config/urxvt/config"
urxvtd -f -q

xsetroot -cursor_name left_ptr

pkill sxhkd
sxhkd &
python3 "${CJ_DOTFILES}/tools/update_monitor_setup.py" &
dunst &
vertical_bar &
redshift &

# Base

bspc monitor -d {1..12}

# Controls

bspc config focus_follows_pointer true
bspc config pointer_modifier mod1

# Theming

bspc config active_border_color "#${CJ_COLOR_4_HEX}"
bspc config focused_border_color "#${CJ_COLOR_4_HEX}"
bspc config normal_border_color "#${CJ_COLOR_0_HEX}"
bspc config presel_feedback_color "#${CJ_COLOR_DIM_BLACK_HEX}"

bspc config border_width 2
bspc config window_gap   24

bspc config single_monocle true
bspc config borderless_monocle true
bspc config gapless_monocle    true
