dictionaries = [
    "en_us",
    "ru",
]

words = [
    "Fontconfig",
    "Gnupg",
    "Hyprland",
    "Paru",
    "Tmux",
    "Waybar",
    "XDG",
    "Zathura",
    "breakindent",
    "cmdheight",
    "cursorline",
    "expandtab",
    "folke",
    "formatoptions",
    "fuzzel",
    "gitcommit",
    "gitsigns",
    "hypr",
    "indentexpr",
    "ipython",
    "jumpoptions",
    "laststatus",
    "ledgerrc",
    "lesskey",
    "listchars",
    "mpv",
    "psqlrc",
    "pypoetry",
    "scrolloff",
    "shiftwidth",
    "sidescrolloff",
    "signcolumn",
    "smartcase",
    "smoothscroll",
    "softtabstop",
    "splitbelow",
    "splitright",
    "statusline",
    "swapfile",
    "tabstop",
    "termux",
    "textwidth",
    "timeoutlen",
    "undofile",
    "unnamedplus",
    "updatetime",
    "wlr",
    "zprofile",
]

[[overrides]]
paths = "**/*.lua"
exclude_tags = ["identifier"]
