dictionaries = [
    "en_us",
    "en_gb",
    "ru",
    "fr",
]
words = [
    "ASNS",
    "BBF",
    "DPM",
    "Fontconfig",
    "Gnupg",
    "Hyprland",
    "NSDI",
    "Paru",
    "Sbercloud",
    "TRASHBIN",
    "Tmux",
    "Todoist",
    "Waybar",
    "XDG",
    "Zathura",
    "aiodns",
    "bgp",
    "bgpd",
    "breakindent",
    "cmdheight",
    "convinient",
    "cursorline",
    "exif",
    "expandtab",
    "eza",
    "fillfactor",
    "folke",
    "formatoptions",
    "fuzzel",
    "fzf",
    "gitcommit",
    "gitsigns",
    "gzip",
    "histsize",
    "hypr",
    "hyprland",
    "indentexpr",
    "inote",
    "ipython",
    "jumpoptions",
    "laststatus",
    "ledgerrc",
    "lesskey",
    "listchars",
    "listmax",
    "lol",
    "lst",
    "minimalistic",
    "mkdir",
    "mpv",
    "mrt",
    "neovim",
    "psql",
    "psqlrc",
    "pypoetry",
    "qrator",
    "qwen",
    "rprompt",
    "savehist",
    "scrolloff",
    "setopt",
    "shiftwidth",
    "sidescrolloff",
    "signcolumn",
    "smartcase",
    "smoothscroll",
    "softtabstop",
    "splitbelow",
    "splitright",
    "statusline",
    "stockfish",
    "swapfile",
    "syslog",
    "tablespace",
    "tabstop",
    "termux",
    "textwidth",
    "timeoutlen",
    "tmux",
    "tokisuno",
    "uci",
    "undofile",
    "unforunate",
    "unlogged",
    "unnamedplus",
    "updatetime",
    "webgl",
    "wlr",
    "zoxide",
    "zprofile",
    "zstyle",
    "Верхнеуровневый",
    "Дисклеймер",
    "ИИ",
    "Лайв",
    "Разогревочные",
    "допушить",
    "кеширования",
    "кодинг",
]

[[overrides]]
paths = "**/*.lua"
exclude_tags = ["identifier"]
