general {
  lock_cmd         = pidof hyprlock || hyprlock --grace 10; makoctl reload

  before_sleep_cmd = loginctl lock-session
  after_sleep_cmd  = niri msg action power-on-monitors
  inhibit_sleep    = 3  # mode=3 -- wait until session is locked before suspending
}

# Send notification before locking
listener {
  timeout = 540  # 9 minutes
  on-timeout = notify-send -u critical -c lock-notification "󰌾 Locking screen" "\nScreen will lock in 1 minute"
}

# Lock the screen after inactivity
listener {
  timeout = 600  # 10 minutes
  on-timeout = loginctl lock-session
}

# Turn off monitor faster when it's locked
listener {
  timeout = 15
  ignore_inhibit = true  # we're locked already, so just in case let's ignore any inhibit signals
  on-timeout = pidof hyprlock && niri msg action power-off-monitors
}

# Turn off monitor after locking the screen
listener {
  timeout = 615  # 10 minutes + 15 seconds
  ignore_inhibit = true  # we're locked already, so just in case let's ignore any inhibit signals
  on-timeout = pidof hyprlock && niri msg action power-off-monitors
}

# Suspend after 20 minutes of inactivity, if locked (only on battery)
listener {
  timeout = 1200  # 20 minutes
  ignore_inhibit = true
  on-timeout = pidof hyprlock && ! systemd-ac-power && systemctl suspend
}
