general {
  lock_cmd = pidof hyprlock || hyprlock; makoctl reload
}

# Send notification before locking
listener {
  timeout = 540  # 9 minutes
  on-timeout = notify-send -u critical -i /usr/share/icons/breeze-dark/status/64/security-medium.svg "Inactivity detected" "Locking screen in 1 minute"
}

# Lock the screen after inactivity
listener {
  timeout = 600  # 10 minutes
  on-timeout = pidof hyprlock || hyprlock; makoctl reload
}

# Turn off monitor faster when it's locked
listener {
  timeout = 15
  ignore_inhibit = true
  on-timeout = pidof hyprlock && niri msg action power-off-monitors
}

listener {
  timeout = 615  # 10 minutes + 15 seconds
  ignore_inhibit = true
  on-timeout = niri msg action power-off-monitors
}

