general {
  lock_cmd = pidof hyprlock || hyprlock
}

# Lock the screen after inactivity
listener {
  timeout = 600  # 10 minutes
  on-timeout = pidof hyprlock || loginctl lock-session
}

# Turn off monitor faster when it's locked
listener {
  timeout = 15
  on-timeout = pidof hyprlock && niri msg action power-off-monitors
}

