general {
  disable_loading_bar = false
  hide_cursor = true
  ignore_empty_input = true
  immediate_render = true
  fractional_scaling = 0
  fail_timeout = 1000
}

background {
  color = rgb(${bg_dim_more})
}

input-field {
  size = 500, 75
  position = 0, 0

  fade_on_empty = true
  dots_size = 0.2
  dots_spacing = 0.5
  outline_thickness = 3
  placeholder_text =
  fail_text =

  outer_color = rgb(${bg})
  inner_color = rgb(${bg})
  font_color = rgb(${fg})
  check_color = rgb(${blue})
  fail_color = rgb(${red})
  capslock_color = rgb(${orange})

  shadow_passes = 1
  shadow_size = 8
  shadow_boost = 0.6
}

label {
  text = cmd[update:10000] TZ=Asia/Bangkok date "+%H:%M"
  position = 0, @scale(150)  # SCALE: 150

  color = rgba(${blue}80)

  font_size = @scale(75)  # SCALE: 75
  font_family = Noto Sans Mono Thin
}

label {
  text = cmd[update:10000] TZ=Asia/Bangkok date "+%e %B, %A"
  position = 0, @scale(75)  # SCALE: 75

  color = rgba(${blue}80)

  font_size = @scale(25)  # SCALE: 25
  font_family = Noto Sans Mono Light
}
