# Default download dir
dir=${HOME}/downloads/aria

# I usually have very bad internet, so no seeding :(
seed-time=0

# Speed up some downloads
disable-ipv6=true
file-allocation=falloc
bt-enable-lpd=true

# For bad networks
max-connection-per-server=8
retry-wait=5

# Resume downloads on restart
continue=true
