#!/usr/bin/env python

import psutil
import time


def main():
    battery = psutil.sensors_battery()
    if not battery:
        return print("(box)", flush=True)

    if battery.power_plugged:
        icon = ""  # fa-battery-full
        color = "#98D6B3"  # green
    elif battery.secsleft <= 600:
        icon = ""  # fa-battery-empty
        color = "#ED7291"
    elif battery.percent <= 12.5:
        icon = ""  # fa-battery-empty
        color = "#ED7291"
    elif battery.percent <= 37.5:
        icon = ""  # fa-battery-quarter
        color = "#E1BD76"
    elif battery.percent <= 62.5:
        icon = ""  # fa-battery-half
        color = "#BBC5DB"
    elif battery.percent <= 87.5:
        icon = ""  # fa-battery-three-quarters
        color = "#BBC5DB"
    else:
        icon = ""  # fa-battery-full
        color = "#BBC5DB"

    minutes = round(battery.secsleft / 60)

    percent = f"{round(battery.percent)}%, {minutes} minutes left"

    print(
        f"""
        (label
            :class "battery"
            :text "{icon}"
            :tooltip "{percent}"
            :style "color: {color}"
        )
        """.replace("\n", " "),
        flush=True,
    )


while True:
    main()
    time.sleep(60)
