#!/usr/bin/env python

import sys


def main():
            # :text ""
    print(
        f"""
        (box
            :orientation "vertical"
            ""
            "100"
        )
        """.replace("\n", ""),
        flush=True,
    )


main()
for line in sys.stdin:
    main()
