feh --no-fehbg --bg-tile "${CJ_WALLPAPER}"

setxkbmap -layout "us,ru" -option "grp:caps_toggle,grp_led:caps,grp_led:scroll,grp_led:num,compose:ralt"

if command -v picom > /dev/null; then
  picom --daemon --experimental-backends
fi

exec i3
