#!/usr/bin/env python

import shutil
import sys
from dataclasses import dataclass


@dataclass
class Binary:
    name: str
    binary: str

    def exists(self) -> bool:
        return shutil.which(self.binary) is not None


DEPENDENCIES = [
    # Core
    Binary(name="Z Shell", binary="zsh"),
    Binary(name="fd", binary="fd"),
    Binary(name="eza", binary="eza"),

    # CLI Tools
    Binary(name="Git", binary="git"),
    Binary(name="diff-so-fancy", binary="diff-so-fancy"),

    Binary(name="fzf", binary="fzf"),
    Binary(name="zoxide", binary="zoxide"),

    Binary(name="Less", binary="less"),
    Binary(name="Curl", binary="curl"),
    Binary(name="OpenSSH", binary="ssh"),
    Binary(name="OpenGPG", binary="gpg"),
    Binary(name="Tmux", binary="tmux"),
    Binary(name="Htop", binary="htop"),
    Binary(name="psql", binary="psql"),
    Binary(name="pass", binary="pass"),
    Binary(name="termdown", binary="termdown"),
    Binary(name="rg", binary="rg"),
    Binary(name="pinentry-tty", binary="pinentry-tty"),
    Binary(name="watchexec", binary="watchexec"),

    # Development
    Binary(name="Ruff", binary="ruff"),
    Binary(name="Cargo", binary="cargo"),
    Binary(name="Poetry", binary="poetry"),
    Binary(name="UV", binary="uv"),

    # LSP Servers
    Binary(name="Taplo (TOML LSP)", binary="taplo"),
    Binary(name="Codebook (spell checking LSP)", binary="codebook-lsp"),
    Binary(name="prettierd", binary="prettierd"),

    # Arch linux
    Binary(name="paru", binary="paru"),

    # Sound
    Binary(name="wpctl", binary="wpctl"),
    Binary(name="pavucontrol", binary="pavucontrol"),

    # WM
    Binary(name="NiriWM", binary="niri"),
    Binary(name="Foot Terminal", binary="foot"),
    Binary(name="Mako", binary="mako"),
    Binary(name="Waybar", binary="waybar"),
    Binary(name="Fuzzel", binary="fuzzel"),
    Binary(name="Hyprlock", binary="hyprlock"),
    Binary(name="Hypridle", binary="hypridle"),

    # GUI Apps
    Binary(name="Google Chrome (unstable)", binary="google-chrome-unstable"),
    Binary(name="Zathura", binary="zathura"),
    Binary(name="MPV", binary="mpv"),

    # Gui Utils
    Binary(name="brightnessctl", binary="brightnessctl"),
    Binary(name="flameshot", binary="flameshot"),
    Binary(name="swaybg", binary="swaybg"),
    Binary(name="libnotify", binary="notify-send"),
    Binary(name="wl-clipboard", binary="wl-copy"),
    Binary(name="cliphist", binary="cliphist"),
    Binary(name="wtype", binary="wtype"),
]


def warn(message: str) -> None:
    _ = sys.stderr.write(f"× WARNING: {message}\n")  # noqa: RUF001


def main() -> None:
    for dep in DEPENDENCIES:
        if not dep.exists():
            warn(
                f"binary `{dep.binary}` for "
                f'dependency "{dep.name}" doesn\'t exist'
            )


if __name__ == "__main__":
    main()
