[main]
# Fonts
font=Noto Sans Mono Light:pixelsize=@scale(12),Arundina Sans Mono:pixelsize=@scale(19)  # SCALE: 12, 19
font-bold=Noto Sans Mono Light:pixelsize=@scale(12)  # SCALE: 12
font-italic=Noto Sans Mono Light:pixelsize=@scale(12):slant=italic  # SCALE: 12
font-bold-italic=Noto Sans Mono Light:pixelsize=@scale(12):slant=italic  # SCALE: 12

# Fonts fine-tuning
vertical-letter-offset=-1
line-height=@scale(14)px  # SCALE: 14
underline-thickness=@scale(1)px  # SCALE: 1
underline-offset=@scale(2)px  # SCALE: 2

# Styling
bold-text-in-bright=palette-based
pad=@scale(16)x@scale(16) center  # SCALE: 16, 16
initial-window-size-chars=80x30
resize-by-cells=no

# Misc
term=xterm
locked-title=yes
selection-target=both
workers=0
utmp-helper=none

# Colors
gamma-correct-blending=false

[bell]
urgent=yes

[scrollback]
lines=10000

[cursor]
beam-thickness=@scale(1)  # SCALE: 1

[mouse]
hide-when-typing=yes

[key-bindings]
clipboard-paste=Control+v Control+Shift+v

scrollback-up-page=none
scrollback-down-page=none
scrollback-up-half-page=Shift+Page_Up
scrollback-down-half-page=Shift+Page_Down
scrollback-up-line=Shift+Up
scrollback-down-line=Shift+Down

# Send the current scrollback buffer to nvim for editing
pipe-scrollback=[sh -c "t=$$(mktemp); cat > $$t; footclient nvim +'$$' $$t"] Control+Shift+e

[mouse-bindings]
primary-paste=none

[tweak]
scaling-filter=none
font-monospace-warn=no
grapheme-width-method=wcswidth  # necessary to make emoji not too wide

grapheme-shaping=no
sixel=no

# Group recieved text updates and apply them all at once
# With minimal 60fps (16ms) and maximum of 120fps (8ms)
delayed-render-lower=8000000
delayed-render-upper=16000000

[colors-dark]
cursor=${bg} ${fg_half_dim}

background=${bg}
foreground=${fg}

selection-foreground=${fg}
selection-background=${bg_sel}

regular0=${bg}
regular1=${red}
regular2=${green}
regular3=${yellow}
regular4=${blue}
regular5=${purple}
regular6=${cyan}
regular7=${fg_half_dim}

bright0=${fg_dim}
bright1=${orange}
bright2=${green}
bright3=${yellow}
bright4=${blue}
bright5=${pink}
bright6=${cyan}
bright7=${fg}

dim0=${fg_dim}
dim1=${orange}
dim2=${green}
dim3=${yellow}
dim4=${blue}
dim5=${pink}
dim6=${cyan}
dim7=${fg}
