[main]
# Fonts
# VAR: text_font_size
# VAR: text_font_size
font=NotoSansM NFM Light:pixelsize={text_font_size},Arundina Sans Mono:pixelsize={text_font_size}
# VAR: text_font_size
# VAR: text_font_size
font-bold=NotoSansM NFM Light:pixelsize={text_font_size},Arundina Sans Mono:pixelsize={text_font_size}
# VAR: text_font_size
# VAR: text_font_size
font-italic=NotoSansM NFM Light:pixelsize={text_font_size}:slant=italic,Arundina Sans Mono:pixelsize={text_font_size}:slant=italic
# VAR: text_font_size
# VAR: text_font_size
font-bold-italic=NotoSansM NFM Light:pixelsize={text_font_size}:slant=italic,Arundina Sans Mono:pixelsize={text_font_size}:slant=italic

# Fonts fine-tuning
# NOTE: shift font a bit, so g is not cut off at the bottom
vertical-letter-offset=-1
# SCALE: 16.5
line-height={16.5}px
# SCALE: 1
underline-thickness={1}px
# SCALE: 2
underline-offset={2}px
# SCALE: 1
strikeout-thickness={1}px

# Styling
bold-text-in-bright=palette-based
# SCALE: 16
# SCALE: 21.3
pad={16}x{21.3} center
initial-window-size-chars=80x30
resize-by-cells=no

# Misc
term=xterm
locked-title=yes
selection-target=both
workers=0
utmp-helper=none

# Colors
gamma-correct-blending=false

[bell]
urgent=yes

[scrollback]
lines=10000

[cursor]
# SCALE: 1
beam-thickness={1}

[mouse]
hide-when-typing=yes

[key-bindings]
clipboard-paste=Control+v Control+Shift+v

scrollback-up-page=none
scrollback-down-page=none
scrollback-up-half-page=Shift+Page_Up
scrollback-down-half-page=Shift+Page_Down
scrollback-up-line=Shift+Up
scrollback-down-line=Shift+Down

# Send the current scrollback buffer to nvim for editing
pipe-scrollback=[sh -c "t=$(mktemp); cat > $t; footclient nvim +'$' $t"] Control+Shift+e

# Open URLs from the visible text
pipe-visible=[sh -c "xurls | uniq | tac | fuzzel --dmenu | xargs -r $BROWSER"] Control+u

[mouse-bindings]
primary-paste=none

[tweak]
scaling-filter=none
font-monospace-warn=no
grapheme-width-method=wcswidth  # necessary to make emoji not too wide

grapheme-shaping=no
sixel=no

# Group recieved text updates and apply them all at once
# With minimal 60fps (16ms) and maximum of 120fps (8ms)
delayed-render-lower=8000000
delayed-render-upper=16000000

[colors-dark]
# VAR: bg
# VAR: fg_half_dim
cursor={bg} {fg_half_dim}

# VAR: bg
background={bg}
# VAR: fg
foreground={fg}

# VAR: fg
selection-foreground={fg}
# VAR: bg_sel
selection-background={bg_sel}

# VAR: bg
regular0={bg}
# VAR: red
regular1={red}
# VAR: green
regular2={green}
# VAR: yellow
regular3={yellow}
# VAR: blue
regular4={blue}
# VAR: purple
regular5={purple}
# VAR: cyan
regular6={cyan}
# VAR: fg_half_dim
regular7={fg_half_dim}

# VAR: fg_dim
bright0={fg_dim}
# VAR: orange
bright1={orange}
# VAR: green
bright2={green}
# VAR: yellow
bright3={yellow}
# VAR: blue
bright4={blue}
# VAR: pink
bright5={pink}
# VAR: cyan
bright6={cyan}
# VAR: fg
bright7={fg}

# VAR: fg_dim
dim0={fg_dim}
# VAR: orange
dim1={orange}
# VAR: green
dim2={green}
# VAR: yellow
dim3={yellow}
# VAR: blue
dim4={blue}
# VAR: pink
dim5={pink}
# VAR: cyan
dim6={cyan}
# VAR: fg
dim7={fg}

# Dark Green (diff add background)
# VAR: bg_add
22={bg_add}

# Dark Red (diff remove background)
# VAR: bg_remove
52={bg_remove}
